### ISSUE TITLE
Feature install fails with "Unable to locate package azure-functions-core-tools"

### ISSUE THREAD

**Issue by burkeholland** [jlaundry/devcontainers-feature-azure-functions-core-tools#12]
**System:** Windows 11 : WSL Ubuntu-18.04
**VS Code Stable**: 1.81.1
**Dev Containers Extension**: v0.305.0

The container build fails when including the feature. It looks as if apt-get is failing, but when running the install command from the script locally, it works fine. This occurs as root user as well. Relevant portion of the logs...

```
#0 0.585 (*) Installing Azure Functions Core Tools...
#0 1.328 MICROSOFT_GPG_KEYS_URI=https://packages.microsoft.com/keys/microsoft.asc
#0 1.895 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#0 1.979 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
#0 2.015 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#0 2.015 Get:4 https://packages.microsoft.com/debian/12/prod bookworm InRelease [3597 B]
#0 2.066 Get:5 http://deb.debian.org/debian bookworm/main amd64 Packages [8906 kB]
[2023-08-16T18:25:01.845Z] #0 2.294 Get:6 https://packages.microsoft.com/debian/12/prod bookworm/main all Packages [342 B]
#0 2.355 Get:7 https://packages.microsoft.com/debian/12/prod bookworm/main amd64 Packages [7481 B]
#0 3.847 Get:8 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [4732 B]
#0 3.848 Get:9 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [57.2 kB]
[2023-08-16T18:25:01.845Z] 
#0 4.952 Fetched 9231 kB in 3s (2835 kB/s)
#0 4.952 Reading package lists...
#0 5.762 Reading package lists...
[2023-08-16T18:25:01.846Z] 
#0 6.433 Building dependency tree...
#0 6.728 Reading state information...
#0 6.742 E: Unable to locate package azure-functions-core-tools
```

Full Log: https://gist.github.com/burkeholland/27c88bf3150b439149eb1492baec150e

**Comment by jlaundry** [comment]
Hi @burkeholland - as per the mentioned issue, Microsoft have not yet released a .deb version for bookworm.

(This is the case for most of their Linux apps - most notably for me, PowerShell, `msodbc`, and Defender for Endpoint are also missing from the Debian 12 package lists).

**Comment by log2** [comment]
Hi @jlaundry , @burkeholland , it seems that the same holds for ARM64-version of such packages, in this case both for bullseye and for bookworm. Can you confirm? Are there any alternatives?

Thank you

**Comment by jlaundry** [comment]
@log2 bookworm still isn't supported on any architecture (https://github.com/Azure/azure-functions-core-tools/issues/3431), and while Microsoft have added ARM64 for macOS (via Homebrew), there's still no sign of any Linux ARM64 support: https://github.com/Azure/azure-functions-core-tools/issues/3112

Please comment on those issues, and if you have a Microsoft account manager, tell them too: Microsoft seem to react when lots of people make noise.

**Comment by mboiman** [comment]
not working :(

**Comment by jlaundry** [comment]
@burkeholland @mboiman try now - it looks like Bookworm support silently shipped with release 4.0.5571!

**Comment by pleberre** [comment]
Linux-Arm64 is really a must. Quite difficult to comprehend why this isn't yet available.

**Comment by mboiman** [comment]
@jlaundry thanks i will try on next possibility
